import placeholderImages from './placeholder-images.json';

export const allMemberDocuments: Record<string, any[]> = {
  '1': [ // Jane Doe
    {
      id: 'doc1',
      name: 'Annual Check-up Results',
      type: 'Lab Report',
      date: '2023-10-18',
      tags: ['lab-results', 'check-up', 'annual', 'physical-exam'],
      patientInfo: { name: 'Jane Doe', dob: '1990-05-21', patientId: 'JD-12345' },
      reportInfo: { reportId: 'RPT-98765', issuedBy: 'Dr. Emily Carter', facility: 'Central City Clinic', time: '09:45 AM' },
      vitalSigns: { bloodPressure: '120/80 mmHg', heartRate: '72 bpm', temperature: '98.6°F (37°C)', respiratoryRate: '16 breaths/min' },
      labResults: [
        { test: 'Total Cholesterol', value: '210 mg/dL', range: 'Below 200 mg/dL', status: 'High' },
        { test: 'LDL Cholesterol', value: '140 mg/dL', range: 'Below 130 mg/dL', status: 'High' },
        { test: 'HDL Cholesterol', value: '60 mg/dL', range: 'Above 40 mg/dL', status: 'Normal' },
        { test: 'Triglycerides', value: '110 mg/dL', range: 'Below 150 mg/dL', status: 'Normal' },
        { test: 'Blood Glucose', value: '90 mg/dL', range: '70-100 mg/dL', status: 'Normal' },
      ],
      assessment: 'Patient appears to be in good health overall, though cholesterol levels are slightly elevated. Vitals are stable. No other acute issues identified.',
      recommendations: 'Recommend dietary consultation to manage cholesterol. Continue with regular exercise. Re-test cholesterol in 3 months. Schedule next annual physical exam in one year.',
    },
    {
      id: 'doc2',
      name: 'MRI Scan - Left Knee',
      type: 'Imaging Report',
      date: '2023-09-05',
      tags: ['imaging', 'orthopedics', 'mri'],
      patientInfo: { name: 'Jane Doe', dob: '1990-05-21', patientId: 'JD-12345' },
      reportInfo: { reportId: 'RPT-98766', issuedBy: 'Dr. Alan Grant', facility: 'Island Imaging Center', time: '03:15 PM' },
      vitalSigns: {},
      labResults: [],
      assessment: 'MRI of the left knee shows a moderate tear of the medial meniscus. No other significant abnormalities noted. The anterior cruciate ligament is intact.',
      recommendations: 'Referral to an orthopedic specialist for consultation regarding surgical vs. non-surgical management options. Recommend RICE (Rest, Ice, Compression, Elevation) protocol in the interim.',
      images: [
        {
          src: placeholderImages.mriScan.src,
          width: placeholderImages.mriScan.width,
          height: placeholderImages.mriScan.height,
          alt: placeholderImages.mriScan.alt,
          hint: placeholderImages.mriScan.hint,
        },
        {
          src: placeholderImages.mriScan2.src,
          width: placeholderImages.mriScan2.width,
          height: placeholderImages.mriScan2.height,
          alt: placeholderImages.mriScan2.alt,
          hint: placeholderImages.mriScan2.hint,
        },
      ],
    },
    {
      id: 'doc3',
      name: 'Prescription - Amoxicillin',
      type: 'Prescription',
      date: '2023-08-22',
      tags: ['prescription', 'pharmacy'],
      patientInfo: { name: 'Jane Doe', dob: '1990-05-21', patientId: 'JD-12345' },
      reportInfo: { reportId: 'RPT-98767', issuedBy: 'Dr. Emily Carter', facility: 'Central City Clinic', time: '11:00 AM' },
      vitalSigns: {},
      labResults: [],
      assessment: 'Diagnosis: Acute Sinusitis. Prescribing Amoxicillin to treat bacterial infection.',
      recommendations: 'Take one 500mg tablet twice daily for 10 days. Complete the full course of antibiotics even if feeling better. Avoid alcohol. May cause mild stomach upset.'
    },
    {
      id: 'doc4',
      name: 'Dental X-Ray',
      type: 'Imaging Report',
      date: '2023-07-11',
      tags: ['dental', 'imaging', 'x-ray'],
      patientInfo: { name: 'Jane Doe', dob: '1990-05-21', patientId: 'JD-12345' },
      reportInfo: { reportId: 'RPT-98768', issuedBy: 'Dr. Ian Malcolm', facility: 'Downtown Dental', time: '02:00 PM' },
      vitalSigns: {},
      labResults: [],
      assessment: 'Bitewing and panoramic X-rays reviewed. Early signs of a cavity (caries) on tooth #30 (lower right first molar). No other signs of decay or periodontal disease.',
      recommendations: 'Schedule a filling for tooth #30. Continue regular brushing and flossing. Six-month follow-up recommended.',
      images: [
          {
            src: placeholderImages.dentalXray.src,
            width: placeholderImages.dentalXray.width,
            height: placeholderImages.dentalXray.height,
            alt: placeholderImages.dentalXray.alt,
            hint: placeholderImages.dentalXray.hint,
          },
        ],
    },
    {
      id: 'doc5',
      name: 'Allergy Test Results',
      type: 'Lab Report',
      date: '2023-06-15',
      tags: ['lab-results', 'allergy'],
      patientInfo: { name: 'Jane Doe', dob: '1990-05-21', patientId: 'JD-12345' },
      reportInfo: { reportId: 'RPT-98769', issuedBy: 'Dr. Ellie Sattler', facility: 'Allergy & Asthma Associates', time: '10:30 AM' },
      vitalSigns: {},
      labResults: [
          { test: 'Dust Mites (D. farinae)', value: 'Class 3', range: 'Negative', status: 'High' },
          { test: 'Cat Dander', value: 'Class 4', range: 'Negative', status: 'High' },
          { test: 'Ragweed Pollen', value: 'Class 2', range: 'Negative', status: 'Moderate' },
          { test: 'Peanut', value: 'Class 0', range: 'Negative', status: 'Normal' },
      ],
      assessment: 'Patient has a significant allergy to dust mites and cat dander, and a moderate allergy to ragweed pollen. No allergy to peanuts detected.',
      recommendations: 'Discussed environmental control measures for dust mites and cats. Prescribed an antihistamine for seasonal allergy symptoms. Recommended allergen-proof bedding. Follow up as needed.'
    },
    {
      id: 'doc6',
      name: 'Abdominal Ultrasound',
      type: 'Imaging Report',
      date: '2023-05-20',
      tags: ['imaging', 'ultrasound', 'gastroenterology'],
      patientInfo: { name: 'Jane Doe', dob: '1990-05-21', patientId: 'JD-12345' },
      reportInfo: { reportId: 'RPT-98770', issuedBy: 'Dr. John Hammond', facility: 'Central City Clinic', time: '01:30 PM' },
      vitalSigns: {},
      labResults: [],
      assessment: 'Ultrasound of the abdomen reveals a normal-appearing liver, gallbladder, spleen, pancreas, and kidneys. No evidence of gallstones or other abnormalities.',
      recommendations: 'No follow-up needed based on these findings. Patient can continue with routine care.',
      images: [
        {
          src: placeholderImages.ultrasoundScan.src,
          width: placeholderImages.ultrasoundScan.width,
          height: placeholderImages.ultrasoundScan.height,
          alt: placeholderImages.ultrasoundScan.alt,
          hint: placeholderImages.ultrasoundScan.hint,
        },
      ],
    },
  ],
  '2': [ // John Doe
    {
      id: 'doc7',
      name: 'Pre-employment Physical',
      type: 'Lab Report',
      date: '2024-01-20',
      tags: ['physical-exam', 'employment', 'lab-results'],
      patientInfo: { name: 'John Doe', dob: '1988-11-15', patientId: 'JD-54321' },
      reportInfo: { reportId: 'RPT-98771', issuedBy: 'Dr. Emily Carter', facility: 'Corporate Health Services', time: '11:00 AM' },
      vitalSigns: { bloodPressure: '125/82 mmHg', heartRate: '68 bpm', temperature: '98.5°F (36.9°C)', respiratoryRate: '15 breaths/min' },
      labResults: [
        { test: 'Vision Test', value: '20/20', range: 'N/A', status: 'Normal' },
      ],
      assessment: 'Patient is fit for employment. No significant health issues noted.',
      recommendations: 'None.',
    },
  ],
  '3': [ // Jimmy Doe
    {
      id: 'doc8',
      name: 'Immunization Record',
      type: 'Vaccination Record',
      date: '2023-09-01',
      tags: ['vaccination', 'school-form', 'pediatrics'],
      patientInfo: { name: 'Jimmy Doe', dob: '2015-03-10', patientId: 'JD-Child1' },
      reportInfo: { reportId: 'RPT-98772', issuedBy: 'Dr. Emily Chen', facility: 'Pediatric Care Center', time: '10:00 AM' },
      vitalSigns: {},
      labResults: [],
      assessment: 'All childhood immunizations are up to date as per the recommended schedule. MMR and Varicella administered today.',
      recommendations: 'Next check-up in 1 year.',
    },
  ],
  '4': [ // Jonna Doe
    {
      id: 'doc9',
      name: 'School Entry Physical',
      type: 'Physical Exam',
      date: '2024-02-15',
      tags: ['physical-exam', 'school-form', 'pediatrics'],
      patientInfo: { name: 'Jonna Doe', dob: '2018-07-22', patientId: 'JD-Child2' },
      reportInfo: { reportId: 'RPT-98773', issuedBy: 'Dr. Emily Chen', facility: 'Pediatric Care Center', time: '02:00 PM' },
      vitalSigns: { height: '119 cm', weight: '22 kg' },
      labResults: [],
      assessment: 'Healthy child, developing normally. Vision and hearing screenings passed.',
      recommendations: 'Encourage a balanced diet and active play.',
    },
    {
      id: 'doc10',
      name: 'Chest X-Ray',
      type: 'Imaging Report',
      date: '2024-03-01',
      tags: ['imaging', 'x-ray', 'pediatrics'],
      patientInfo: { name: 'Jonna Doe', dob: '2018-07-22', patientId: 'JD-Child2' },
      reportInfo: { reportId: 'RPT-98774', issuedBy: 'Dr. Alan Grant', facility: 'Island Imaging Center', time: '09:30 AM' },
      vitalSigns: {},
      labResults: [],
      assessment: 'Chest X-ray taken due to persistent cough. Lungs are clear. No signs of pneumonia or other infiltrates. Heart size is normal. The findings are unremarkable.',
      recommendations: 'Cough is likely viral. Continue to monitor.',
      images: [
          {
            src: placeholderImages.chestXray.src,
            width: placeholderImages.chestXray.width,
            height: placeholderImages.chestXray.height,
            alt: placeholderImages.chestXray.alt,
            hint: placeholderImages.chestXray.hint,
          },
        ],
    },
  ],
};
