// This file is automatically generated by the Firebase setup.
// Do not edit this file manually.

import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: 'AIzaSyBI5VZsIk5mXE0yMckWLSrwS8cOFXOoaUs',
  authDomain: 'health-passport-rs9b1.firebaseapp.com',
  projectId: 'health-passport-rs9b1',
  storageBucket: 'health-passport-rs9b1.appspot.com',
  messagingSenderId: '885921956861',
  appId: '1:885921956861:web:4634fb1bda05fea7a08f94',
};
